Traceback (most recent call last):
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/tune/trial_runner.py", line 240, in _process_events
    result = self.trial_executor.fetch_result(trial)
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py", line 200, in fetch_result
    result = ray.get(trial_future[0])
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/worker.py", line 2366, in get
    raise RayGetError(object_ids, value)
ray.worker.RayGetError: Could not get objectid ObjectID(01000000e9d3ea6da9b26bfe5d2f70e4b95dfc33). It was created by remote function [31mtrain[39m which failed with:

Remote function [31mtrain[39m failed with:

Traceback (most recent call last):
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/worker.py", line 856, in _process_task
    *arguments)
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/function_manager.py", line 481, in actor_method_executor
    method_returns = method(actor, *args)
  File "/home/hua/tesp/tesp/maml/maml.py", line 222, in train
    results = Agent.__base__.train(self)
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/tune/trainable.py", line 146, in train
    result = self._train()
  File "/home/hua/tesp/tesp/maml/maml.py", line 189, in _train
    fetches = self.optimizer.step()
  File "/home/hua/tesp/tesp/maml/maml_optimizer.py", line 88, in step
    last_weights = self.sync_weights()
  File "/home/hua/tesp/tesp/maml/maml_optimizer.py", line 33, in sync_weights
    for e in self.remote_evaluators])
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/worker.py", line 2358, in get
    raise RayGetError(object_ids[i], value)
ray.worker.RayGetError: Could not get objectid ObjectID(0100000025473243dbcec12b029def8fda94e930). It was created by remote function [31mset_weights[39m which failed with:

Remote function [31mset_weights[39m failed with:

Traceback (most recent call last):
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/worker.py", line 834, in _process_task
    self.memory_monitor.raise_if_low_memory()
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/ray/memory_monitor.py", line 72, in raise_if_low_memory
    total_gb = psutil.virtual_memory().total / 1e9
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/psutil/__init__.py", line 2088, in virtual_memory
    ret = _psplatform.virtual_memory()
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/psutil/_pslinux.py", line 395, in virtual_memory
    with open_binary('%s/meminfo' % get_procfs_path()) as f:
  File "/home/hua/.conda/envs/metarl/lib/python3.6/site-packages/psutil/_common.py", line 604, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/meminfo'


